// Display names only. Stored codes and command payloads remain unchanged.
const labels: Record<string, string> = {
  all: 'הכול', admin: 'מנהל', technician: 'טכנאי', customer: 'לקוח',
  system: 'מערכת', provider: 'ספק התשלום', worker: 'תהליך רקע',
  pending_payment: 'ממתינה לתשלום', paid: 'שולמה', processing: 'בהכנה',
  shipped: 'נשלחה', delivered: 'נמסרה', cancelled: 'בוטלה',
  payment_expired: 'תוקף התשלום פג', refunded: 'הוחזרה',
  awaiting_intake_review: 'ממתינה לבדיקת הפנייה',
  awaiting_diagnostic_payment: 'ממתינה לתשלום אבחון',
  awaiting_admin_review: 'ממתינה לבדיקת מנהל', scheduled: 'מתואמת',
  received: 'המכונה התקבלה', diagnosing: 'באבחון',
  awaiting_additional_decision: 'ממתינה לאישור הצעת תיקון',
  awaiting_additional_payment: 'ממתינה לתשלום תיקון',
  repair_in_progress: 'בתיקון', ready_for_return: 'מוכנה להחזרה', completed: 'הושלמה',
  pending: 'ממתין', accepted: 'אושרה', rejected: 'נדחתה', declined: 'נדחתה',
  confirmed: 'אושר', failed: 'נכשל', sent: 'נשלח', dead_letter: 'הניסיונות הופסקו',
  sending: 'בשליחה', retrying: 'בניסיון חוזר', retry: 'ניסיון חוזר',
  service_intake: 'פנייה', service_issue: 'תיאור התקלה',
  service_diagnosis: 'אבחון', service_repair: 'תיקון',
  issue: 'תקלה', diagnosis: 'אבחון', repair: 'תיקון',
  coffee_machine: 'מכונת קפה', machine: 'מכונת קפה', beans: 'פולי קפה',
  capsules: 'קפסולות', spare_part: 'חלק חילוף', accessory: 'אביזר',
  'catalog.category_created': 'יצירת קטגוריה', 'catalog.category_updated': 'עדכון קטגוריה',
  'catalog.product_created': 'יצירת מוצר', 'catalog.product_updated': 'עדכון מוצר', 'catalog.product_images_updated': 'עדכון תמונות מוצר',
  'catalog.sku_created': 'יצירת מק״ט', 'catalog.sku_updated': 'עדכון מק״ט',
  'catalog.machine_model_created': 'יצירת דגם מכונה', 'catalog.machine_model_updated': 'עדכון דגם מכונה',
  'inventory.stock_corrected': 'תיקון מלאי', 'user.access_changed': 'שינוי הרשאות',
  'notification.delivery_retried': 'ניסיון שליחה נוסף',
  'service.note_added': 'הוספת הערת שירות', 'service.assignment_changed': 'שינוי שיבוץ טכנאי',
  category: 'קטגוריה', product: 'מוצר', product_sku: 'מק״ט', sku: 'מק״ט',
  machine_model: 'דגם מכונה', service_request: 'בקשת שירות',
  notification_delivery: 'שליחת התראה', user: 'משתמש',
};
export const label = (value: string) => labels[value] ?? 'לא ידוע';
export const productTypeLabel = (value: string) => labels[value] ?? value;
