import { expect } from '@playwright/test';
import { api, confirm, createCustomer, test, type Schema } from './staffFixtures';

test('admin configures service, reviews fees, schedules overlaps and completes paid and no-cost repairs with a technician', async ({ staff }) => {
  test.setTimeout(180_000);
  const page = await staff.admin.newPage();
  const technicianPage = await staff.technician.newPage();
  const request = staff.admin.request;
  const admin = staff.adminSession.access_token;
  const tech = staff.technicianSession;
  const suffix = Date.now().toString();
  const phone = `055${suffix.slice(-7)}`;
  const customer = await createCustomer(request, phone);
  const name = `Service browser ${suffix}`;
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  technicianPage.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/configuration');
  await page.getByRole('button', { name: 'דגם מכונה חדש' }).click();
  await page.getByLabel('יצרן', { exact: true }).fill('Browser');
  await page.getByLabel('שם הדגם', { exact: true }).fill(name);
  await page.getByRole('button', { name: 'שמירת דגם מכונה', exact: true }).click();
  await expect(page.getByRole('button', { name: `עריכה ${name}`, exact: true })).toBeVisible();
  const models: Schema['MachineModelRead'][] = await (await api(request, admin, '/admin/machine-models')).json();
  const model = models.find((item) => item.model_name === name)!;
  await page.getByRole('link', { name: 'סוגי שירות', exact: true }).click();
  await page.getByRole('button', { name: 'סוג שירות חדש', exact: true }).click();
  await page.getByLabel('שם השירות בעברית').fill(`תיקון ${suffix}`);
  await page.getByLabel('שם השירות באנגלית').fill(name);
  await page.getByRole('combobox', { name: 'סמל שירות', exact: true }).selectOption('coffee');
  await page.getByLabel('תגיות בעברית').fill('בדיקת דפדפן');
  await page.getByLabel('מחיר התחלתי באגורות').fill('5000');
  await page.getByLabel(`Browser ${name}`, { exact: true }).check();
  await page.getByRole('button', { name: 'סקירת סוג השירות', exact: true }).click();
  await confirm(page, 'שמירת סוג שירות');
  const types: Schema['ServiceTypeRead'][] = await (await api(request, admin, '/admin/service-types')).json();
  const type = types.find((item) => item.label_en === name)!;
  const machine: Schema['RegisteredMachineRead'] = await (await api(request, customer, '/machines', { machine_model_id: model.id, serial_number: `BROWSER-${suffix}` })).json();
  const options: Schema['ServiceIntakeOptionsRead'] = await (await api(request, customer, `/machines/${machine.id}/service-options`)).json();
  const urgency = options.urgencies[0];
  const create = async () => (await (await api(request, customer, `/machines/${machine.id}/service-requests`, { service_type_id: type.id, description: 'Coffee machine leaks during brewing.', location_mode: 'bring_in', urgency_id: urgency.id, intake_version: options.version })).json()) as Schema['ServiceRequestRead'];
  const first = await create();
  const second = await create();
  const unpaid = await create();
  const appointmentDay = new Date(Date.now() + 86400000).toISOString().slice(0, 10);
  for (const [index, item] of [first, second].entries()) {
    await page.goto(`/service/${item.id}`);
    await expect(page.getByRole('heading', { name: item.reference, exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: 'סקירת תיאום', exact: true })).toHaveCount(0);
    await page.getByLabel('דמי אבחון בסיסיים באגורות').fill('10000');
    await page.getByRole('button', { name: 'סקירת דמי אבחון', exact: true }).click();
    await confirm(page, 'שליחת הצעת אבחון');
    await expect(page.getByText(/ממתינים לתשלום דמי האבחון/)).toBeVisible();
    const intent: Schema['ServicePaymentIntentRead'] = await (await api(request, customer, `/service-requests/${item.id}/diagnostic-payment`, undefined, 'POST', `diagnostic-${item.id}`)).json();
    await api(request, admin, '/test/payments/webhooks', { event_id: `diag-${item.id}`, event_type: 'payment_intent.succeeded', provider_object_id: intent.provider_payment_id, state: 'confirmed' });
    await page.getByRole('button', { name: 'רענון הבקשה', exact: true }).click();
    await page.getByRole('combobox', { name: 'טכנאי', exact: true }).selectOption(tech.user_id);
    await page.getByLabel('תחילת התיאום (שעון ישראל)').fill(`${appointmentDay}T10:00`);
    await page.getByLabel('סיום התיאום (שעון ישראל)').fill(`${appointmentDay}T11:00`);
    await page.getByRole('button', { name: 'סקירת תיאום', exact: true }).click();
    await expect(page.locator('.outcome')).toBeVisible();
    if (index === 1) {
      await expect(page.getByRole('heading', { name: 'חפיפות בתיאום', exact: true })).toBeVisible();
      const before: Schema['StaffServiceRequestRead'] = await (await api(request, admin, `/admin/service-requests/${item.id}`)).json();
      expect(before.state).toBe('awaiting_admin_review');
    }
    if (await page.getByLabel('המשך למרות החפיפות בתיאום').isVisible()) await page.getByLabel('המשך למרות החפיפות בתיאום').check();
    await confirm(page, 'אישור תיאום');
    await technicianPage.goto('/jobs');
    await technicianPage.getByRole('link', { name: item.reference, exact: true }).click();
    await expect(technicianPage.getByText(`BROWSER-${suffix}`, { exact: true })).toBeVisible();
    await confirm(technicianPage, 'סימון המכונה כהתקבלה');
    await confirm(technicianPage, 'התחלת אבחון');
    await technicianPage.getByLabel('הערה', { exact: true }).fill(`Internal inspection ${index}`);
    await technicianPage.getByRole('button', { name: 'הוספת הערה', exact: true }).click();
    await expect(technicianPage.locator('.note-list').getByText(`Internal inspection ${index}`, { exact: true })).toBeVisible();
    if (index === 0) {
      await technicianPage.getByLabel('תמונת עבודה', { exact: true }).setInputFiles({ name: 'diagnosis.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6xJ8AAAAASUVORK5CYII=', 'base64') });
      await technicianPage.getByRole('button', { name: 'העלאת תמונת עבודה', exact: true }).click();
      await technicianPage.getByRole('button', { name: 'טעינת קובץ אבחון', exact: true }).click();
      await expect(technicianPage.getByRole('link', { name: 'פתיחת קובץ אבחון', exact: true })).toBeVisible();
    }
    expect(await technicianPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.getByRole('button', { name: 'רענון הבקשה', exact: true }).click();
    await page.getByLabel('הערה', { exact: true }).fill(`Customer update ${index}`);
    await page.getByRole('combobox', { name: 'למי ההערה גלויה', exact: true }).selectOption('customer');
    await page.getByRole('button', { name: 'הוספת הערה', exact: true }).click();
    await expect(page.locator('.note-list').getByText(`Customer update ${index}`, { exact: true })).toBeVisible();
    const customerView: Schema['ServiceRequestRead'] = await (await api(request, customer, `/service-requests/${item.id}`)).json();
    expect(customerView.notes.map((note) => note.body)).toEqual([`Customer update ${index}`]);
    if (index === 0) {
      await page.getByLabel('עלות נוספת בסיסית באגורות').fill('20000');
      await page.getByLabel('הסבר גלוי ללקוח').fill('Replace the worn pump');
      await page.getByRole('button', { name: 'סקירת הצעה נוספת', exact: true }).click();
      await confirm(page, 'שליחת הצעה נוספת');
      await api(request, customer, `/service-requests/${item.id}/quote-decision`, { decision: 'accepted' });
      await technicianPage.getByRole('button', { name: 'רענון הבקשה', exact: true }).click();
      await expect(technicianPage.getByText(/התיקון מושהה/)).toBeVisible();
      await expect(technicianPage.getByRole('button', { name: 'סימון כמוכנה להחזרה', exact: true })).toHaveCount(0);
      const payment: Schema['ServicePaymentIntentRead'] = await (await api(request, customer, `/service-requests/${item.id}/additional-payment`, undefined, 'POST', `additional-${item.id}`)).json();
      await api(request, admin, '/test/payments/webhooks', { event_id: `extra-${item.id}`, event_type: 'payment_intent.succeeded', provider_object_id: payment.provider_payment_id, state: 'confirmed' });
    } else await confirm(page, 'התחלת תיקון ללא עלות נוספת');
    await technicianPage.getByRole('button', { name: 'רענון הבקשה', exact: true }).click();
    await confirm(technicianPage, 'סימון כמוכנה להחזרה');
    await page.getByRole('button', { name: 'רענון הבקשה', exact: true }).click();
    // Leave the first request open until the second appointment tests overlap detection.
    if (index === 1) await confirm(page, 'סיום השירות');
  }
  await page.goto(`/service/${first.id}`);
  await confirm(page, 'סיום השירות');
  await expect(page.locator('.record-header .status-badge').first()).toHaveText('הושלמה');
  await page.goto(`/service/${unpaid.id}`);
  await page.getByLabel('סיבת הביטול').fill('Duplicate intake request');
  await confirm(page, 'ביטול השירות');
  await expect(page.locator('.record-header .status-badge').first()).toHaveText('בוטלה');
  await page.goto('/configuration/shop');
  await expect(page.getByRole('heading', { name: 'כתובת להבאת המכונה', exact: true })).toBeVisible();
  await page.goto('/overview');
  await expect(page.getByLabel('בקשות שירות פתוחות', { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
  await page.screenshot({ path: test.info().outputPath('overview.png'), fullPage: true });
  await technicianPage.screenshot({ path: test.info().outputPath('technician.png'), fullPage: true });
  await page.close(); await technicianPage.close();
});
